### ISSUE TITLE
Setup a HomeAssistant playground repository

### ISSUE THREAD

**Issue by Its-Alex** [Its-Alex/backlog#37]
I would like to setup a [HomeAssistant](https://www.hacf.fr/) server in my home, to automate installation and configuration I would like to create a playground.

I would like to make those things works:

- [ ] Music server
- [ ] Sonos
- [x] Meross LAN
- [ ] Matter
- [x] Zigbee
- [ ] ...

**Comment by Its-Alex** [comment]
I create the playground: https://github.com/Its-Alex/homeassistant-docker-playground

**Comment by Its-Alex** [comment]
The POC is currently working on Linux with podman, I need to do these adjustments:

- [x] Allow container to speak with hosts and other container in docker network
- [x] Add more documentation about how to setup Zigbee2MQTT

**Comment by Its-Alex** [comment]
> Allow container to speak with hosts and other container in docker network

Since I'm using [podman](https://podman.io/), I don't want to include specific code in the [playground](https://github.com/Its-Alex/homeassistant-docker-playground)

A solution with docker is to assign a local IP to the container and private IP for the docker network, for example:

```yaml
  networks:
      macvlan:
        ipv4_address: 192.168.1.220
        priority: 100
      web:
        priority: 10
      default:
        priority: 10
```
